// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFH2v3Y1IURZV8R9eGMSmBu_xwjTDwQf0',
    appId: '1:455623518149:web:123ef0e00fb75247e20dac',
    messagingSenderId: '455623518149',
    projectId: 'projfp4',
    authDomain: 'projfp4.firebaseapp.com',
    storageBucket: 'projfp4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCICWW14w8cPmAMxrd95TpWFWnpxdEIK7Q',
    appId: '1:455623518149:android:07a75dc2a4ab9bf1e20dac',
    messagingSenderId: '455623518149',
    projectId: 'projfp4',
    storageBucket: 'projfp4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeD3KVEzxr-nYYynu2CcVTvxrOiegENOk',
    appId: '1:455623518149:ios:43ec5df321463c4fe20dac',
    messagingSenderId: '455623518149',
    projectId: 'projfp4',
    storageBucket: 'projfp4.appspot.com',
    iosBundleId: 'com.example.fp4',
  );
}
